services:
  backend:
    image: ghcr.io/get-convex/convex-backend:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "4001:3210"
      - "4003:3211"
    volumes:
      - data:/convex/data
    environment:
      - CONVEX_CLOUD_ORIGIN=http://127.0.0.1:4001
      - CONVEX_SITE_ORIGIN=http://127.0.0.1:4003
      - DOCUMENT_RETENTION_DELAY=172800
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3210"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s


  dashboard:
    image: ghcr.io/get-convex/convex-dashboard:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "4002:6791"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=http://127.0.0.1:4001
    depends_on:
      backend:
        condition: service_healthy

volumes:
  data:
